# Generated by Django 4.0.2 on 2022-02-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
