# Generated by Django 4.0.2 on 2022-03-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_composition_alter_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
