# Generated by Django 4.0.2 on 2022-03-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Many_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='publications',
            field=models.ManyToManyField(to='store.Many_tag'),
        ),
    ]
