# Generated by Django 4.0.2 on 2022-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_many_tag_product_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publications',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ManyToManyField(null=True, to='store.Category'),
        ),
        migrations.DeleteModel(
            name='Many_tag',
        ),
    ]
