# Generated by Django 4.0.2 on 2022-03-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_category_name_remove_product_publications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
