# Generated by Django 4.0.2 on 2022-03-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_title_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
