# Generated by Django 4.0.2 on 2022-03-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
